# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-11-10 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urban', '0003_auto_20191110_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='post',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='SOME STRING', upload_to='photos/'),
        ),
    ]
